export type MonthlyPlan = {
  km: string;
  price: number;
  bookingUrl: string;
};

export type VehicleItem = {
  id: number;
  slug: string;
  name: string;
  image: string;
  category: string;
  seats: number;
  bags: number;
  doors: number;
  transmission: string;
  fuel: string;
  minimumDays: number;
  dailyPrice: number;
  weeklyPrice: number;
  monthlyPrice: number;
  allowNoDeposit: boolean;
  showRefundableDeposit: boolean;
  noDepositFee: number;
  monthlyPlans: MonthlyPlan[];
};

export const vehicleData: VehicleItem[] = [
  {
    id: 1,
    slug: "nissan-sunny",
    name: "Nissan Sunny",
    image: "/vehicle/nissan-sunny.jpg",
    category: "Sedan",
    seats: 5,
    bags: 2,
    doors: 4,
    transmission: "Automatic",
    fuel: "Petrol",
    minimumDays: 1,
    dailyPrice: 75,
    weeklyPrice: 70,
    monthlyPrice: 1300,
    allowNoDeposit: true,
    showRefundableDeposit: false,
    noDepositFee: 59,
    monthlyPlans: [
      { price: 1300, km: "1500 KM", bookingUrl: "/booking/nissan-sunny?plan=1500" },
      { price: 1650, km: "3000 KM", bookingUrl: "/booking/nissan-sunny?plan=3000" },
      { price: 1850, km: "5000 KM", bookingUrl: "/booking/nissan-sunny?plan=5000" },
      { price: 2100, km: "7500 KM", bookingUrl: "/booking/nissan-sunny?plan=7500" },
    ],
  },
  {
    id: 2,
    slug: "mitsubishi-attrage",
    name: "Mitsubishi Attrage",
    image: "/vehicle/mitsubishi-attrage.jpg",
    category: "Sedan",
    seats: 5,
    bags: 2,
    doors: 4,
    transmission: "Automatic",
    fuel: "Petrol",
    minimumDays: 1,
    dailyPrice: 75,
    weeklyPrice: 70,
    monthlyPrice: 1350,
    allowNoDeposit: true,
    showRefundableDeposit: false,
    noDepositFee: 59,
    monthlyPlans: [
      { price: 1350, km: "1500 KM", bookingUrl: "/booking/mitsubishi-attrage?plan=1500" },
      { price: 1700, km: "3000 KM", bookingUrl: "/booking/mitsubishi-attrage?plan=3000" },
      { price: 1900, km: "5000 KM", bookingUrl: "/booking/mitsubishi-attrage?plan=5000" },
      { price: 2150, km: "7500 KM", bookingUrl: "/booking/mitsubishi-attrage?plan=7500" },
    ],
  },
  {
    id: 3,
    slug: "suzuki-ciaz",
    name: "Suzuki Ciaz",
    image: "/vehicle/suzuki-ciaz.jpg",
    category: "Sedan",
    seats: 5,
    bags: 3,
    doors: 4,
    transmission: "Automatic",
    fuel: "Petrol",
    minimumDays: 1,
    dailyPrice: 95,
    weeklyPrice: 90,
    monthlyPrice: 1600,
    allowNoDeposit: true,
    showRefundableDeposit: false,
    noDepositFee: 59,
    monthlyPlans: [
      { price: 1600, km: "1500 KM", bookingUrl: "/booking/suzuki-ciaz?plan=1500" },
      { price: 1900, km: "3000 KM", bookingUrl: "/booking/suzuki-ciaz?plan=3000" },
      { price: 2150, km: "5000 KM", bookingUrl: "/booking/suzuki-ciaz?plan=5000" },
      { price: 2400, km: "7500 KM", bookingUrl: "/booking/suzuki-ciaz?plan=7500" },
    ],
  },
  {
    id: 4,
    slug: "nissan-magnite",
    name: "Nissan Magnite",
    image: "/vehicle/nissan-magnite.jpg",
    category: "SUV",
    seats: 5,
    bags: 3,
    doors: 4,
    transmission: "Automatic",
    fuel: "Petrol",
    minimumDays: 1,
    dailyPrice: 110,
    weeklyPrice: 100,
    monthlyPrice: 1700,
    allowNoDeposit: true,
    showRefundableDeposit: false,
    noDepositFee: 59,
    monthlyPlans: [
      { price: 1700, km: "1500 KM", bookingUrl: "/booking/nissan-magnite?plan=1500" },
      { price: 2000, km: "3000 KM", bookingUrl: "/booking/nissan-magnite?plan=3000" },
      { price: 2250, km: "5000 KM", bookingUrl: "/booking/nissan-magnite?plan=5000" },
      { price: 2500, km: "7500 KM", bookingUrl: "/booking/nissan-magnite?plan=7500" },
    ],
  },
  {
    id: 5,
    slug: "hyundai-creta",
    name: "Hyundai Creta",
    image: "/vehicle/hyundai-creta.jpg",
    category: "SUV",
    seats: 5,
    bags: 3,
    doors: 4,
    transmission: "Automatic",
    fuel: "Petrol",
    minimumDays: 2,
    dailyPrice: 140,
    weeklyPrice: 130,
    monthlyPrice: 2200,
    allowNoDeposit: true,
    showRefundableDeposit: false,
    noDepositFee: 0,
    monthlyPlans: [
      { price: 2200, km: "1500 KM", bookingUrl: "/booking/hyundai-creta?plan=1500" },
      { price: 2500, km: "3000 KM", bookingUrl: "/booking/hyundai-creta?plan=3000" },
      { price: 2800, km: "5000 KM", bookingUrl: "/booking/hyundai-creta?plan=5000" },
      { price: 3100, km: "7500 KM", bookingUrl: "/booking/hyundai-creta?plan=7500" },
    ],
  },
  {
    id: 6,
    slug: "toyota-raize",
    name: "Toyota Raize",
    image: "/vehicle/toyota-raize.jpg",
    category: "SUV",
    seats: 5,
    bags: 3,
    doors: 4,
    transmission: "Automatic",
    fuel: "Petrol",
    minimumDays: 2,
    dailyPrice: 145,
    weeklyPrice: 135,
    monthlyPrice: 2250,
    allowNoDeposit: true,
    showRefundableDeposit: false,
    noDepositFee: 0,
    monthlyPlans: [
      { price: 2250, km: "1500 KM", bookingUrl: "/booking/toyota-raize?plan=1500" },
      { price: 2550, km: "3000 KM", bookingUrl: "/booking/toyota-raize?plan=3000" },
      { price: 2850, km: "5000 KM", bookingUrl: "/booking/toyota-raize?plan=5000" },
      { price: 3150, km: "7500 KM", bookingUrl: "/booking/toyota-raize?plan=7500" },
    ],
  },
  {
    id: 7,
    slug: "mitsubishi-asx",
    name: "Mitsubishi ASX",
    image: "/vehicle/mitsubishi-asx.jpg",
    category: "SUV",
    seats: 5,
    bags: 3,
    doors: 4,
    transmission: "Automatic",
    fuel: "Petrol",
    minimumDays: 2,
    dailyPrice: 150,
    weeklyPrice: 140,
    monthlyPrice: 2300,
    allowNoDeposit: true,
    showRefundableDeposit: false,
    noDepositFee: 0,
    monthlyPlans: [
      { price: 2300, km: "1500 KM", bookingUrl: "/booking/mitsubishi-asx?plan=1500" },
      { price: 2600, km: "3000 KM", bookingUrl: "/booking/mitsubishi-asx?plan=3000" },
      { price: 2900, km: "5000 KM", bookingUrl: "/booking/mitsubishi-asx?plan=5000" },
      { price: 3200, km: "7500 KM", bookingUrl: "/booking/mitsubishi-asx?plan=7500" },
    ],
  },
  {
    id: 8,
    slug: "mitsubishi-xpander",
    name: "Mitsubishi Xpander",
    image: "/vehicle/mitsubishi-xpander.jpg",
    category: "7 Seater",
    seats: 7,
    bags: 4,
    doors: 4,
    transmission: "Automatic",
    fuel: "Petrol",
    minimumDays: 2,
    dailyPrice: 170,
    weeklyPrice: 160,
    monthlyPrice: 2600,
    allowNoDeposit: true,
    showRefundableDeposit: false,
    noDepositFee: 0,
    monthlyPlans: [
      { price: 2600, km: "1500 KM", bookingUrl: "/booking/mitsubishi-xpander?plan=1500" },
      { price: 2950, km: "3000 KM", bookingUrl: "/booking/mitsubishi-xpander?plan=3000" },
      { price: 3300, km: "5000 KM", bookingUrl: "/booking/mitsubishi-xpander?plan=5000" },
      { price: 3650, km: "7500 KM", bookingUrl: "/booking/mitsubishi-xpander?plan=7500" },
    ],
  },
  {
    id: 9,
    slug: "suzuki-ertiga",
    name: "Suzuki Ertiga",
    image: "/cars/suzuki-ertiga-white.png",
    category: "7 Seater",
    seats: 7,
    bags: 4,
    doors: 4,
    transmission: "Automatic",
    fuel: "Petrol",
    minimumDays: 2,
    dailyPrice: 170,
    weeklyPrice: 160,
    monthlyPrice: 2600,
    allowNoDeposit: true,
    showRefundableDeposit: false,
    noDepositFee: 0,
    monthlyPlans: [
      { price: 2600, km: "1500 KM", bookingUrl: "/booking/suzuki-ertiga?plan=1500" },
      { price: 2950, km: "3000 KM", bookingUrl: "/booking/suzuki-ertiga?plan=3000" },
      { price: 3300, km: "5000 KM", bookingUrl: "/booking/suzuki-ertiga?plan=5000" },
      { price: 3650, km: "7500 KM", bookingUrl: "/booking/suzuki-ertiga?plan=7500" },
    ],
  },
];
